### ISSUE TITLE
labelling boolean check backwards?

### ISSUE THREAD

**Issue by shawnjones253** [weaselBuddha/Queue4Download#4]
Are these checks backwards (the `if $LABELLING -eq 0` part)? It's late and I could be misreading 😄 

https://github.com/weaselBuddha/Queue4Download/blob/0939cd6c5a60ae1f2fee0f50b6f8f36a9dcb61de/Q4D/LFTPtransfer.sh#L90
https://github.com/weaselBuddha/Queue4Download/blob/0939cd6c5a60ae1f2fee0f50b6f8f36a9dcb61de/Q4D/Queue4Download.sh#L208

**Comment by weaselBuddha** [comment]
Bash Booleans are weird let me check this.

**Comment by weaselBuddha** [comment]
I think it is fixed.

Checked in with a simple change, the boolean wasn't up front and wasn't being evaluated.  Queue4Download.sh and LFTPtransfer.sh updated,  Additionally not tested as a boolean, my bad.

Apologies for the delay. been a rough week.

**Comment by shawnjones253** [comment]
no need to apologize! appreciate you taking a look :)
